// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG2IcHgsd1EFnJnYXKg6ZABD6qTikYl6Q',
    appId: '1:1002501064445:web:6a2c6ce3115a738dcde094',
    messagingSenderId: '1002501064445',
    projectId: 'bloom-f7ac3',
    authDomain: 'bloom-f7ac3.firebaseapp.com',
    storageBucket: 'bloom-f7ac3.firebasestorage.app',
    measurementId: 'G-X9T9LCZFW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVw5ldgrJ0cnBp51iYz33-oO1n4T1wtYs',
    appId: '1:1002501064445:android:e84b35b5cda47ddacde094',
    messagingSenderId: '1002501064445',
    projectId: 'bloom-f7ac3',
    storageBucket: 'bloom-f7ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRdSfVIepgNT3Jaby3OLRHFuxqj0wQ1E',
    appId: '1:1002501064445:ios:e70a361687519eaacde094',
    messagingSenderId: '1002501064445',
    projectId: 'bloom-f7ac3',
    storageBucket: 'bloom-f7ac3.firebasestorage.app',
    iosBundleId: 'com.example.bloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRdSfVIepgNT3Jaby3OLRHFuxqj0wQ1E',
    appId: '1:1002501064445:ios:e70a361687519eaacde094',
    messagingSenderId: '1002501064445',
    projectId: 'bloom-f7ac3',
    storageBucket: 'bloom-f7ac3.firebasestorage.app',
    iosBundleId: 'com.example.bloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG2IcHgsd1EFnJnYXKg6ZABD6qTikYl6Q',
    appId: '1:1002501064445:web:19c3a68c25c61909cde094',
    messagingSenderId: '1002501064445',
    projectId: 'bloom-f7ac3',
    authDomain: 'bloom-f7ac3.firebaseapp.com',
    storageBucket: 'bloom-f7ac3.firebasestorage.app',
    measurementId: 'G-4P6KM6DWCP',
  );
}
